/*
Marcelo Morales - lmoral10
Peter Novello - pnovell1
*/

DROP TABLE IF EXISTS Video;
DROP TABLE IF EXISTS UserProfile;
DROP TABLE IF EXISTS Song;
DROP TABLE IF EXISTS Artist;
DROP TABLE IF EXISTS Album;
DROP TABLE IF EXISTS Revenue;
DROP TABLE IF EXISTS Player;